[package]
name = "sage-inspector"
version = "0.1.0"
edition.workspace = true

[dependencies]
axum = "0.8"
futures-util = "0.3"
mime_guess = "2"
rust-embed = "8"
sage-reflect = { path = "../sage-reflect" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"

[dev-dependencies]
http-body-util = "0.1.5"
percent-encoding = "2.3.2"
snapbox = "0.6.24"
tower = { version = "0.5.3", features = ["util"] }
