[book]
title = "Symposiun AGentic Environment (SAGE)"
authors = ["Niko Matsakis"]
language = "en"
src = "md"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
optional = true
